config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :categories do
    resources :bills, only: [:new, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true }
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :bills

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bills, foreign_key: :author_id, dependent: :destroy
  has_many :categories, foreign_key: :user_id, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def new
    @bill = Bill.new
    @category = Category.find(params[:category_id])
  end

  def create
    @bill = Bill.new(bill_params)
    @bill.author = current_user
    @bill.categories << Category.find(params[:category_id])
    if @bill.save
      redirect_to category_path(params[:category_id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bill_params
    params.require(:bill).permit(:name, :amount)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    return unless user_signed_in?

    @categories = current_user.categories.includes(:bills)
  end

  def show
    @category = Category.find(params[:id])
    @bills = @category.bills.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.create(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bills/new.html.erb
<div class="container w-full flex flex-col text-center">
  <%= form_with model: @bill, url: category_bills_url, method: :post do |f| %>
    <div class="mb-3 flex flex-col w-full">
      <%= f.text_field :name, placeholder: "Item name", class: "form-inputs" %>
      <div class="gray-bar"></div>
      <%= f.text_field :amount, placeholder: "Amount", class: "form-inputs" %>
      <div class="gray-bar"></div>
      <%= f.select :category_id, options_for_select([['Select Category', '']] + Category.all.map { |c| [c.name, c.id] }), {}, { class: "form-inputs" } %>
    </div>
    <%= f.submit "Add Item", class: "btn-primary" %>
  <% end %>
</div>

app/views/categories/index.html.erb
<% if user_signed_in? %>
  <div class="container flex flex-col">
    <h2 class="pl-4 text-sky-400 font-semibold mb-3">Welcome <%= current_user.name %>!</h2>
    <div class="container flex flex-col items-center gap-4">
      <% @categories.each do |category| %>
        <div class="container flex justify-between px-4 items-center w-11/12 h-20 bg-white mx-4">
          <img src="<%= category.icon %>" class="w-12 h-12" />
          <p><%= link_to category.name, category_path(category), class: "hover:text-sky-400" %></p>
          <p><%= category.bills.map { |bill| bill.amount }.sum %>$</p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="w-full h-20 bg-green-500/100 flex items-center justify-center mt-auto fixed bottom-0">
    <%= link_to "Add Category", new_category_path, class: "btn-secondary w-11/12 text-center" %>
  </div>
<% else %>
  <div class="container h-3/4 flex flex-col justify-between">
    <h1 class="text-center text-4xl font-bold mt-32">Budget Tracker</h1>
    <div class="mt-12 flex flex-col text-center align-middle gap-8 items-center">
      <%= link_to "LOG IN", new_user_session_path, class: 'w-11/12 btn-primary' %>
      <%= link_to "SIGN UP", new_user_registration_path %>
    </div>
  </div>
<% end %>

app/views/categories/new.html.erb
<div class="container w-full flex flex-col text-center">
  <%= form_with model: @category, url: categories_path, method: :post do |f| %>
    <div class="mb-3 flex flex-col w-full">
      <%= f.text_field :name, placeholder: "Category name", class: "form-inputs" %>
      <div class="gray-bar"></div>
      <%= f.text_field :icon, placeholder: "Icon URL", class: "form-inputs" %>
    </div>
    <%= f.submit "Add Category", class: "btn-primary" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="container flex flex-col items-center gap-3">
  <% if @bills.empty? %>
    <p class="text-center text-2xl">No items added yet</p>
  <% end %>
  <% @bills.each do |bill| %>
    <div class="container flex justify-between px-8 items-center w-11/12 h-16 bg-white mx-4">
      <p><%= bill.name %></p>
      <div class="w-1/2 flex items-center justify-center gap-5">
        <small class="text-xs"><%= bill.created_at.strftime("%a %b %Y") %></small>
        <p><%= bill.amount %>$</p>
      </div>
    </div>
  <% end %>
  <div class="w-full h-20 bg-green-500/100 flex items-center justify-center mt-auto fixed bottom-0">
    <%= link_to 'Add Item', new_category_bill_path(@category), class: "btn-secondary w-11/12 text-center" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="flex justify-between h-14 bg-sky-600 items-center px-5 mb-4">
        <% if controller_name == 'categories' && action_name == 'index' %>
          <button id="hamburger-button" class="text-white hover:text-gray-700 focus:outline-none">
            <i class="fas fa-bars fa-2x"></i>
          </button>
          <h1 class="text-white text-xl ml-4">Category List</h1>
        <% elsif controller_name == 'categories' && action_name == 'new' %>
          <%= link_to root_path do %>
            <i class="fas fa-arrow-left mr-2 text-xl text-white"></i>
          <% end %>
          <h1 class="text-white text-xl ml-4">New Category</h1>
        <% elsif controller_name == 'categories' && action_name == 'show' %>
          <%= link_to root_path do %>
            <i class="fas fa-arrow-left mr-2 text-xl text-white"></i>
          <% end %>
          <h1 class="text-white text-xl ml-4">Bills</h1>
        <% else %>
          <%= link_to root_path do %>
            <i class="fas fa-arrow-left mr-2 text-xl text-white"></i>
          <% end %>
          <h1 class="text-white text-xl ml-4">New Bill</h1>
        <% end %>
        <%= link_to "Sign Out", destroy_user_session_path, class: "text-white text-sm" %>
      </nav>
    <% end %>

    <main class="container mx-auto flex flex-col h-full items-center">
      <div class="mx-4">
        <small><%= notice %></small>
        <small><%= alert %></small>
      </div>
      <%= yield %>
    </main>
  </body>
</html>